### ISSUE TITLE
unknown function or script

### ISSUE THREAD

**Issue by duepooong** [GameMakerDiscord/execute_string#1]
Script: __function_execute_1512678626657_facebook_init at line 2 : unknown function or script facebook_init
Script: __function_execute_1512678626657_facebook_login at line 2 : unknown function or script facebook_login
Script: __function_execute_1512678626657_facebook_status at line 2 : unknown function or script facebook_status
Script: __function_execute_1512678626657_facebook_graph_request at line 2 : unknown function or script facebook_graph_request
Script: __function_execute_1512678626657_facebook_dialog at line 2 : unknown function or script facebook_dialog
Script: __function_execute_1512678626657_facebook_logout at line 2 : unknown function or script facebook_logout
Script: __function_execute_1512678626657_facebook_launch_offerwall at line 2 : unknown function or script facebook_launch_offerwall
Script: __function_execute_1512678626657_facebook_post_message at line 2 : unknown function or script facebook_post_message
Script: __function_execute_1512678626657_facebook_send_invite at line 2 : unknown function or script facebook_send_invite
Script: __function_execute_1512678626657_facebook_user_id at line 2 : unknown function or script facebook_user_id
Script: __function_execute_1512678626657_facebook_accesstoken at line 2 : unknown function or script facebook_accesstoken
Script: __function_execute_1512678626657_facebook_check_permission at line 2 : unknown function or script facebook_check_permission
Script: __function_execute_1512678626657_facebook_request_read_permissions at line 2 : unknown function or script facebook_request_read_permissions
Script: __function_execute_1512678626657_facebook_request_publish_permissions at line 2 : unknown function or script facebook_request_publish_permissions

these errors appear when I compile
(In Compile Errors)
I think that it can't recognize dist.gml in ext2_function_execute

**Comment by JujuAdams** [comment]
The Facebook functions were removed from GMS2 in a recent update. These function calls should be removed from the extension. I've sent a message to Minty Python to update the repo; in the meantime you can fix this failure to compile by directly editting dist.gml (delete the offending function definitions).

**Comment by duepooong** [comment]
It was just an easy matter. It works very well.

**Comment by duepooong** [comment]
> The Facebook functions were removed from GMS2 in a recent update. These function calls should be removed from the extension. I've sent a message to Minty Python to update the repo; in the meantime you can fix this failure to compile by directly editting dist.gml (delete the offending function definitions).

It was just an easy matter. It works very well.

**Comment by mintypython** [comment]
Thanks for the heads up, those definitions have been removed.
